### ISSUE TITLE
Issue using transaction

### ISSUE THREAD

**Issue by akermabon** [lusakasa/sqorn#15]
Hello,
I can't seem to make transaction work. I want to get the tx and use it later, because I can't use the callback method. I'm using the following exemple with version 0.0.23

```javascript
const sq = sqorn({
    connection: {
        host: 'localhost',
        database: 'db_trad',
        user: 'aurelien',
        password: 'postgres',
        port: 5432
    }
});

(async () => {

    const tx = await sq.transaction();
    const res = await sq
        .from`trad.bcas`
        .return`*`
        .insert({ store_id: 'test', product_code: 'abc', quantity: 10, schedule_id: 1 })
        .one(tx);
})();
```
I get the following error:
> UnhandledPromiseRejectionWarning: TypeError: client.query is not a function
>     at Object.query (/home/aurelien/workspace/sandbox/node_modules/sqorn-pg/src/database.js:26:35)
>     at Function.one (/home/aurelien/workspace/sandbox/node_modules/sqorn-core/src/index.js:27:33)
>     at /home/aurelien/workspace/sandbox/pg/sqorn.js:19:10

What am I doing wrong ?

**Comment by eejdoowad** [comment]
You're not doing anything wrong.

I designed the transaction API but only provided a rough implementation I thought would work (but never tested).  I'll try to get it working and tested today.

The library is still a work in progress and will be until a 1.0.0 release, probably in the next two weeks.

**Comment by eejdoowad** [comment]
I've fixed the issue and added transaction tests in #16. This change has been published in sqorn v0.0.24.

Let me know if you have any issues.

**Comment by akermabon** [comment]
Hello, I've still got the same issue in version 0.0.24 with the same code

**Comment by eejdoowad** [comment]
Sorry, I messed up when publishing 0.0.24.
0.0.25 contains the fix.
